### ISSUE TITLE
Spotbugs XML output format

### ISSUE THREAD

**Issue by bugh1** [spotbugs/discuss#66]
Is there a documentation or article or any other information regarding the meaning of the XML tags in the XML output? Specifically the meaning of the order and nesting of the XML tags within a BugInstance?

**Comment by uhafner** [comment]
What are you trying to achieve? A new parser that reads the XML?

**Comment by bugh1** [comment]
> What are you trying to achieve? A new parser that reads the XML?

We are trying to translate the spotbugs XML output into a common inter-operable format, SCARF (https://github.com/mirswamp/swamp-scarf-io/blob/master/docs/SCARF.pdf) for the SWAMP project (https://continuousassurance.org/) and SARIF (https://github.com/oasis-tcs/sarif-spec) and it is not immediately obvious how to represent the multiple locations given in the spotbugs output into the code flows in these formats. Any help you could offer to make this the best translation we can would be appreciated.

**Comment by uhafner** [comment]
Ah, I see. You are building something similar to my [analysis-model](
https://github.com/jenkinsci/analysis-model) library that I am using in my [Jenkins Warnings Plugin](
https://github.com/jenkinsci/warnings-ng-plugin) to visualize FindBugs and SpotBugs results. I also tried to write a new parser by reverse engineering the complex structure... I finally ended up using the XML reader provided by the Findbugs library. It works quite well, however be aware that you need to link the whole Findbugs sources, since all classes from several modules (UI, analysis, IO) are distributed as *one* fat jar. 

If you are not interested in multiple locations for each warning, you can also have a look at the [violations-lib](https://github.com/tomasbjerre/violations-lib). It contains a parser that extracts the warnings with the first primary location of the warning.

**Comment by KengoTODA** [comment]
I'll close this inactive issue. Please repost a new one if necessary.
